### ISSUE TITLE
Improved search

### ISSUE THREAD

**Issue by astraldawn** [linkingcharities/linkingcharities-frontend#31]
**Brief description of issue**
Current search feature only allows to search by name. Should be able to search on at least type / target audience

**Comment by royson** [comment]
I think this is more of a design problem as we can group charities into their different types and categories as well as a 'ALL charities' page like we currently do and each individual page has a search bar targeting the specific type.

**Comment by qj** [comment]
You should be able to search by type and target by using the search parameters, e.g. send a GET request to "/api/charities?type=E" for all charities of type E which is Education/Training.

**Comment by astraldawn** [comment]
@junqiangqian is a search by ID allowed also (via a similar format)

**Comment by qj** [comment]
It should be allowed now, I just pushed that change through to master.
